packages/zefyr/CHANGELOG.md
packages/zefyr/example/lib/main.dart
packages/zefyr/lib/src/widgets/input.dart
packages/zefyr/pubspec.yaml

Fixes #11.
This addresses two issues:
1. Ensures that `composing` range is always set to the last known value for data sent to the native side.
2. Prevents sending remote updates if current value (including composing range) is the same the the last known value.
cc @stemuk

Prevents sending excessive value updates to the native side

---

.travis.yml
packages/zefyr/.gitignore
packages/zefyr/lib/src/widgets/buttons.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/selection.dart
packages/zefyr/lib/src/widgets/toolbar.dart
packages/zefyr/test/widgets/editor_test.dart
packages/zefyr/tool/travis.sh

This is first part required for #13 .
Remaining work would be extracting `ZefyrToolbar` into scaffold's `Overlay`.

Toolbar refactor to decouple from editor context

---

packages/zefyr/CHANGELOG.md
packages/zefyr/example/android/app/build.gradle
packages/zefyr/pubspec.yaml

Fixes #80 .
Note that this is a breaking change and requires manual migration from the users. See details in the changelog.

Upgraded dependencies to latest

---

.travis.yml
packages/zefyr/CHANGELOG.md
packages/zefyr/example/lib/src/full_page.dart
packages/zefyr/lib/src/widgets/controller.dart
packages/zefyr/lib/src/widgets/editable_text.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/field.dart
packages/zefyr/lib/src/widgets/mode.dart
packages/zefyr/lib/src/widgets/scaffold.dart
packages/zefyr/lib/src/widgets/scope.dart
packages/zefyr/lib/src/widgets/selection.dart
packages/zefyr/lib/src/widgets/view.dart
packages/zefyr/lib/zefyr.dart
packages/zefyr/pubspec.yaml
packages/zefyr/test/rendering/render_zefyr_paragraph_test.dart
packages/zefyr/test/testing.dart
packages/zefyr/test/widgets/editor_test.dart
packages/zefyr/test/widgets/image_test.dart
packages/zefyr/test/widgets/scope_test.dart
packages/zefyr/test/widgets/selection_test.dart

This is first part of multi-step refactor of selection overlay. Includes following changes:
* Breaking change: `ZefyrEditor.enabled` field replaced by `ZefyrEditor.mode` which can take
one of three default values:
- `ZefyrMode.edit`: the same as `enabled: true`, all editing controls are available to the user
- `ZefyrMode.select`: user can't modify text itself, but allowed to select it and optionally
apply formatting.
- `ZefyrMode.view`: the same as `enabled: false`, read-only.
* Added optional `selectionControls` field to `ZefyrEditor` and `ZefyrEditableText`. If not provided then by default uses platform-specific implementation.
Enables #53 in follow up updates.

Zefyr mode

---

doc/images.md
packages/zefyr/CHANGELOG.md
packages/zefyr/example/lib/src/form.dart
packages/zefyr/example/lib/src/full_page.dart
packages/zefyr/example/lib/src/images.dart
packages/zefyr/example/lib/src/view.dart
packages/zefyr/example/pubspec.yaml
packages/zefyr/lib/src/widgets/buttons.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/image.dart
packages/zefyr/lib/src/widgets/scope.dart
packages/zefyr/lib/src/widgets/toolbar.dart
packages/zefyr/lib/src/widgets/view.dart
packages/zefyr/pubspec.yaml
packages/zefyr/test/testing.dart
packages/zefyr/test/widgets/buttons_test.dart
packages/zefyr/test/widgets/image_test.dart
packages/zefyr/test/widgets/scope_test.dart

* Allows to reduce friction when users want to upgrade their dependencies.
* We only depended on `image_picker` to have default basic implementation of image delegate interface, however was just an example which is unlikely to be used in real-world applications.
* Gets Zefyr one step closer to allow customizing available actions and define 3rd party actions as well.
Addresses #137 , #94 and #82 (partially).

Removed dependency on image_picker plugin

---

packages/notus/CHANGELOG.md
packages/notus/lib/src/document.dart
packages/notus/pubspec.yaml
packages/notus/test/document_test.dart

Fix insertion of embeds when selection is not empty

---

packages/zefyr/lib/src/widgets/input.dart

The new Dart TextInputClient requires the Getter: currentTextEditingValue.
Here you go.
Please review it asap, because we can't build nowhere till now

Fixed new Dart SDK Requirements

---

packages/zefyr/lib/src/widgets/editor.dart

Selection: do not display handles when we do not display the cursor and the selection is collapsed

[1.0-dev] Fix selection handles when hiding cursor

---

packages/zefyr/lib/src/widgets/editor.dart

@cgestes You introduced `_shouldShowSelectionHandles()` in #410 so you might have an opinion on this.
Selection behaviour still isn't on par with pre-v1 Zefyr but this was the first difference I noticed.

Hide selection handle when the current selection is collapsed

---

packages/notus/pubspec.yaml

`meta` package is not used in Notus anymore after migrating to null safety.

Removed meta package from Notus

---

packages/zefyr/example/lib/src/form.dart
packages/zefyr/example/lib/src/full_page.dart
packages/zefyr/example/macos/Podfile.lock
packages/zefyr/example/macos/Runner.xcodeproj/project.pbxproj
packages/zefyr/example/pubspec.yaml
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart
packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
packages/zefyr/lib/src/widgets/editor_toolbar.dart
packages/zefyr/lib/src/widgets/text_line.dart
packages/zefyr/lib/src/widgets/text_selection.dart
packages/zefyr/pubspec.yaml
packages/zefyr/test/testing.dart
packages/zefyr/test/widgets/editor_test.dart

Some of the widget tests are not passing. As far as I found out it isn't because of mine or Flutter 2.x changes. It will be good if you could check it out.
Also the Notus version in pubspec should be changed because of the meta package conflict which was fixed in #511.

Added Flutter 2.x support to Zefyr

---

packages/zefyr/lib/src/rendering/embed_proxy.dart

When caret was at the end of a line with an embed, it was off displayed area, thus invisible to users
This fixes the issue

Fix caret display when cursor on embed line

---

packages/zefyr/lib/src/widgets/text_selection.dart

Swapping handles order is prevented

---

packages/zefyr/lib/src/widgets/editor_toolbar.dart

simple solution to allow prepending or appending widgets on the basic toolbar.

Toolbar.basic: allow to prepend / append buttons

---

packages/notus/lib/src/document/attributes.dart
packages/zefyr/lib/src/rendering/editable_text_block.dart
packages/zefyr/lib/src/rendering/editable_text_line.dart
packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/lib/src/widgets/editable_text_line.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/editor_toolbar.dart
packages/zefyr/lib/src/widgets/rich_text_proxy.dart
packages/zefyr/lib/src/widgets/text_line.dart
packages/zefyr/lib/src/widgets/theme.dart
packages/zefyr/lib/util.dart

I've added text direction support to the both Notus and Zefyr. It matches the behavior of Quill's rich text editor based on my tests.

Added text direction feature

---

packages/zefyr/lib/src/rendering/editable_text_line.dart

Fixes #426.
This is a cherry-pick from https://github.com/memspace/zefyr/pull/543
FYI: @cgestes , thanks again for submitting the fix!

Fix hitTestChildren for the editor

---

packages/notus/lib/src/heuristics/insert_rules.dart
packages/notus/lib/src/heuristics/utils.dart
packages/notus/test/heuristics/insert_rules_test.dart

@cgestes I couldn't find your version in your PR (https://github.com/memspace/zefyr/pull/546) for some reason, so there was no commits to cherry-pick which would be authored by you. 
This implementation is basically the same as in the Gist I shared a while back, just adds some tests and docs.
Does not include the cursor position fix for Zefyr (will be submitted separately).

Markdown block shortcuts

---

packages/notus/CHANGELOG.md
packages/notus/lib/src/heuristics/insert_rules.dart
packages/notus/test/heuristics/insert_rules_test.dart

Adds a special case for code blocks to not require `space` character entered by the user after the shortcut (either ` ``` ` or `'''`). 
Applies the code block style immediately when the shortcut prefix itself is detected.

Markdown shortcuts code block formatting improvement

---

packages/zefyr/lib/src/widgets/editor.dart

Steps to reproduce:
1. Run the example in iOS or Android 
2. Select some text, observe selection toolbar and handles appear
3. Press `delete` to delete the selected text
Expected: selection toolbar and handles should disappear
Actual: selection toolbar and handles still visible
@Amir-P @amantoux @cgestes I'd appreciate if any of you can validate the fix in your projects. From my testing this doesn't seem to break anything else.

Fixed: Hide selection overlay for collapsed selection

---

packages/zefyr/CHANGELOG.md
packages/zefyr/example/lib/src/read_only_view.dart
packages/zefyr/lib/src/widgets/editable_text_block.dart
packages/zefyr/lib/src/widgets/editor.dart
packages/zefyr/lib/src/widgets/keyboard_listener.dart
packages/zefyr/lib/src/widgets/link.dart
packages/zefyr/lib/src/widgets/text_line.dart
packages/zefyr/lib/zefyr.dart

Allows launching links in editing mode, where:
* For desktop platforms: links launch on `Cmd` + `Click` (macOS) or `Ctrl` + `Click` (windows, linux)
* For mobile platforms: long-pressing a link shows a context menu with multiple actions (Open, Copy, Remove) for the user to choose from.
WIP

Launch link improvements
