packages/zefyr/lib/src/widgets/buttons.dart, packages/zefyr/lib/src/widgets/caret.dart, packages/zefyr/lib/src/widgets/code.dart, packages/zefyr/lib/src/widgets/common.dart, packages/zefyr/lib/src/widgets/controller.dart, packages/zefyr/lib/src/widgets/editable_box.dart, packages/zefyr/lib/src/widgets/editable_text.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/image.dart, packages/zefyr/lib/src/widgets/input.dart, packages/zefyr/lib/src/widgets/list.dart, packages/zefyr/lib/src/widgets/paragraph.dart, packages/zefyr/lib/src/widgets/rich_text.dart, packages/zefyr/lib/src/widgets/selection.dart, packages/zefyr/lib/src/widgets/toolbar.dart, packages/zefyr/lib/util.dart
=> Removed 'new' keyword from zefyr package

packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/mode.dart, packages/zefyr/lib/src/widgets/scaffold.dart, packages/zefyr/test/testing.dart, packages/zefyr/test/widgets/editor_test.dart
=> Fix toggling toolbar between two editors

packages/zefyr/example/lib/src/full_page.dart, packages/zefyr/lib/src/widgets/editable_text.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/field.dart, packages/zefyr/lib/src/widgets/input.dart
=> Added support for iOS keyboard appearance

packages/zefyr/lib/src/widgets/selection.dart
Experience closer to TextField when dragging handles
=> Better experience with SelectionHandles

packages/notus/CHANGELOG.md, packages/notus/lib/src/heuristics.dart, packages/notus/lib/src/heuristics/insert_rules.dart, packages/notus/pubspec.yaml, packages/notus/test/heuristics/insert_rules_test.dart, packages/zefyr/lib/src/widgets/editor.dart
No breaking changes here but this makes it a bit easier to work with code blocks.
FYI @cgestes .
=> Block-level heuristics improvements

packages/zefyr/example/pubspec.yaml, packages/zefyr/lib/src/rendering/baseline_proxy.dart, packages/zefyr/lib/src/rendering/cursor_painter.dart, packages/zefyr/lib/src/rendering/editable_box.dart, packages/zefyr/lib/src/rendering/editable_text_block.dart, packages/zefyr/lib/src/rendering/editable_text_line.dart, packages/zefyr/lib/src/rendering/editor.dart, packages/zefyr/lib/src/rendering/embed_proxy.dart, packages/zefyr/lib/src/rendering/paragraph_proxy.dart, packages/zefyr/lib/src/services/keyboard.dart, packages/zefyr/lib/src/widgets/baseline_proxy.dart, packages/zefyr/lib/src/widgets/controller.dart, packages/zefyr/lib/src/widgets/cursor.dart, packages/zefyr/lib/src/widgets/editable_text_block.dart, packages/zefyr/lib/src/widgets/editable_text_line.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart, packages/zefyr/lib/src/widgets/editor_keyboard_mixin.dart, packages/zefyr/lib/src/widgets/editor_toolbar.dart, packages/zefyr/lib/src/widgets/embed_proxy.dart, packages/zefyr/lib/src/widgets/field.dart, packages/zefyr/lib/src/widgets/rich_text_proxy.dart, packages/zefyr/lib/src/widgets/selection_utils.dart, packages/zefyr/lib/src/widgets/text_line.dart, packages/zefyr/lib/src/widgets/text_selection.dart, packages/zefyr/lib/src/widgets/theme.dart, packages/zefyr/pubspec.yaml, packages/zefyr/test/testing.dart, packages/zefyr/test/widgets/controller_test.dart, packages/zefyr/test/widgets/editor_test.dart
I tried to read comments and source code to take the best decisions. Also one of the controller tests is failing right now because of the #513. I will update the Notus version after #514 gets accepted.
=> Migration of Zefyr to null-safety

packages/zefyr/example/lib/quick_start.dart, packages/zefyr/example/lib/src/editor_page.dart, packages/zefyr/example/lib/src/form.dart, packages/zefyr/example/lib/src/full_page.dart, packages/zefyr/example/lib/src/layout_scrollable.dart, packages/zefyr/example/lib/src/scaffold.dart, packages/zefyr/example/lib/src/settings.dart, packages/zefyr/example/macos/Podfile, packages/zefyr/example/macos/Podfile.lock, packages/zefyr/example/macos/Runner.xcodeproj/project.pbxproj, packages/zefyr/lib/src/widgets/editable_text_block.dart, packages/zefyr/lib/src/widgets/editor_toolbar.dart, packages/zefyr/lib/src/widgets/field.dart
=> Minor analyzer fixes

packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart, packages/zefyr/lib/src/widgets/selection_utils.dart
TextSelectionDelegate has a new API
```dart
void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause)
```
It need to be implemented to support copy/paste
=> Fix copy/paste

packages/zefyr/lib/src/rendering/cursor_painter.dart, packages/zefyr/lib/src/rendering/editable_box.dart, packages/zefyr/lib/src/rendering/editable_text_block.dart, packages/zefyr/lib/src/rendering/editable_text_line.dart, packages/zefyr/lib/src/rendering/editor.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/editor_selection_delegate_mixin.dart
When extending selection, have scroll controller jump to the most appropriate offset to display selection extension
Before
https://user-images.githubusercontent.com/17318211/128613932-5ff7715e-559f-4d0b-a055-1ccf28af240a.mov
After
https://user-images.githubusercontent.com/17318211/128613963-90346052-aa06-488d-b63d-bd4962ea161f.mov
=> Bring into view upon selection extension

packages/zefyr/lib/src/services/keyboard.dart, packages/zefyr/lib/src/widgets/editor.dart
=> Fix breaking change in keyboard listener

packages/notus/analysis_options.yaml, packages/notus/lib/src/document/node.dart, packages/notus/pubspec.yaml, packages/notus/test/heuristics/insert_rules_test.dart
=> Fixes lints notus

packages/zefyr/lib/src/rendering/cursor_painter.dart, packages/zefyr/lib/src/rendering/editable_box.dart, packages/zefyr/lib/src/rendering/editable_text_block.dart, packages/zefyr/lib/src/rendering/editable_text_line.dart, packages/zefyr/lib/src/rendering/editor.dart, packages/zefyr/lib/src/widgets/cursor.dart, packages/zefyr/lib/src/widgets/editable_text_block.dart, packages/zefyr/lib/src/widgets/editable_text_line.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart
On iOS, ability to use virtual keyboard as a trackpad.
Closes #88 
https://user-images.githubusercontent.com/17318211/141678553-4d7e6499-61e9-48c0-86d8-f845984db84d.mov
=> iOS - Floating cursor

packages/notus/CHANGELOG.md, packages/notus/lib/src/document.dart, packages/notus/lib/src/heuristics/delete_rules.dart, packages/notus/pubspec.yaml, packages/notus/test/document_test.dart, packages/notus/test/heuristics/delete_rules_test.dart
=> Preserve last newline character on delete

packages/zefyr/CHANGELOG.md, packages/zefyr/lib/src/rendering/editable_text_line.dart, packages/zefyr/lib/src/rendering/paragraph_proxy.dart, packages/zefyr/lib/src/widgets/editable_text_line.dart, packages/zefyr/lib/src/widgets/text_line.dart, packages/zefyr/lib/src/widgets/theme.dart, packages/zefyr/pubspec.yaml
Adds background color and radius decorations to InlineCodeThemeData
Additionally:
* Improves selection rects to have consistent height regardless of individual segment text styles
* Fixes an issue where editable text line would stay subscribed to cursor events.
FYI @Amir-P
=> Inline code improvements

packages/zefyr/lib/src/widgets/editor_input_client_mixin.dart
Refer to #554 for description and previous discussions.
=> Removed _sentRemoteValues

packages/zefyr/CHANGELOG.md, packages/zefyr/lib/src/rendering/editor.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/text_selection.dart
* Adds `Shift` + `Click` support for extending selection
* Adds automatic scrolling while selecting text with mouse
=> Desktop selection improvements

packages/notus/CHANGELOG.md, packages/notus/lib/src/document/attributes.dart, packages/notus/lib/src/heuristics/format_rules.dart, packages/notus/lib/src/heuristics/insert_rules.dart, packages/notus/test/heuristics/format_rules_test.dart, packages/notus/test/heuristics/insert_rules_test.dart
Zefyr counterpart will come after this one is merged and new version of notus is pushed to Pub.
=> Adds support for checklists in Notus

packages/zefyr/lib/src/rendering/editable_text_line.dart, packages/zefyr/lib/src/widgets/editable_text_block.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/editor_toolbar.dart, packages/zefyr/pubspec.yaml, packages/zefyr/test/widgets/editable_text_test.dart
Does not expose theming at this moment as I'm not sure what exactly should be customizable here.
=> Added support for checklists in Zefyr

packages/notus/test/heuristics/insert_rules_test.dart
seems to be working fine 👍🏿 
I tried to keep only the interesting test I had.
only test failing is the last one. I honestly dont remember why I did wrote it. Probably when starting from an empty document. It was the last one in the list of test so it was in response to a bug I encountered somehow.
Feel free to close / or keep what makes sense.
=> Markdown rules: add some tests

packages/zefyr/lib/src/rendering/editor.dart, packages/zefyr/lib/src/widgets/editor.dart, packages/zefyr/lib/src/widgets/shortcuts.dart
Flutter SDK no longer exposes TextEditingActionTarget and internalized the entire shortcut handling logic for desktops. :(
See discussion here for more context: https://github.com/flutter/flutter/pull/90684#issuecomment-1029312785
This is a WIP, still need to clean up a few things.
=> Upgrade for Flutter 2.10
